name: Release
on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled, closed]
    branches: [main]

jobs:
  test-trigger:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow triggered by ${{ github.event_name }} action=${{ github.event.action }}"
